#  NGINX() {
#
#    CHECK_ROOT
#    PRINT "Installing Nginx"
#    yum install nginx -y &>>${LOG}
#    CHECK_STAT $?
#
#    PRINT "Download ${COMPONENT} content"
#    curl -s -L -o /tmp/${COMPONENT}.zip "https://github.com/roboshop-devops-project/${COMPONENT}/archive/main.zip" &>>${LOG}
#    CHECK_STAT $?
#
#    PRINT "Clean old contenct"
#    cd /usr/share/nginx/html && rm -rf * &>>${LOG}
#    CHECK_STAT $?
#
#    PRINT "extract${COMPONENT} content"
#    unzip /tmp/${COMPONENT}.zip &>>${LOG}
#    CHECK_STAT $?
#
#    PRINT "Organize ${COMPONENT} content"
#
#    mv ${COMPONENT}-main/* . && mv static/* . && rm -rf ${COMPONENT}-main README.md && mv localhost.conf /etc/nginx/default.d/roboshop.conf &>>${LOG}
#    CHECK_STAT $?
#
#    for backend in catalogue cart user shipping payment ; do
#    PRINT "Update configuration ${backend}"
#
#    #commented this as part of loop demo, However this single sed command is much better than loop
#    #sed -i -e '/catalogue/ s/localhost/catalogue.roboshop.internal/' -e '/user/ s/localhost/user.roboshop.internal/' -e '/cart/ s/localhost/cart.roboshop.internal/' -e '/shipping/ s/localhost/shipping.roboshop.internal/' -e '/payment/ s/localhost/payment.roboshop.internal/' /etc/nginx/default.d/roboshop.conf
#
#    sed -i -e "/$backend/ s/localhost/$backend.roboshop.internal/" /etc/nginx/default.d/roboshop.conf
#    CHECK_STAT $?
#    done
#
#    PRINT "Start Nginx Service"
#
#    systemctl enable nginx &>>${LOG} && systemctl restart nginx &>>${LOG}
#    CHECK_STAT $?
#
#  }
#
#
#

- name: Install Nginx
  ansible.builtin.yum:
    name: nginx
    state: installed


